### ISSUE TITLE
Russian pluralization

### ISSUE THREAD

**Issue by mr-dxdy** [radar/dotiw#60]
When the english localization, then test succeeds:

``` ruby

it 'When default locale is english' do
  I18n.default_locale = :en

  a = DateTime.parse('2015-05-28 19:00:00')
  b = DateTime.parse('2015-06-19')
  expect( distance_of_time_in_words(a, b, only: :days) ).to eq("21 days")
end
```

But when the russian localization, the test falls:

``` ruby

it 'When default locale is russia' do
  I18n.default_locale = :ru

  a = DateTime.parse('2015-05-28 19:00:00')
  b = DateTime.parse('2015-06-19')
  expect( distance_of_time_in_words(a, b, only: :days) ).to eq("21 день")
end
```

``` ruby
     Failure/Error: expect( distance_of_time_in_words(a, b, only: :days) ).to eq("21 день")
       
       expected: "21 день"
            got: "1 день"
       
       (compared using ==)
```

My gemfile:
``` ruby
  gem 'rails', '4.2.1'
  gem 'russian', '~> 0.6.0'
  gem 'dotiw', '3.0.1'
```

**Comment by Envek** [comment]
Already found in #55 and fixed in #56 . Now tested in rails console:

```ruby
a = DateTime.parse('2015-05-28 19:00:00')
b = DateTime.parse('2015-06-19')
helper.distance_of_time_in_words(a, b, only: :days)
# => "21 день"
```

in Gemfile.lock:

    dotiw (3.0.1)

Please ensure that you have not old version of gem loaded via Spring or something.

**Comment by mr-dxdy** [comment]
Thank you! I saw your [commit](https://github.com/Envek/dotiw/commit/d58bf8cccd587e73764df57215ab79d4a9bafe05) and remembered that in my project has the old file ```config/locales/dotiw.ru.yml```. I deleted a file and it worked.

**Comment by Envek** [comment]
Glad that everything works fine. Please close this issue.

**Comment by dblock** [comment]
I added some spec infrastructure in https://github.com/radar/distance_of_time_in_words/pull/109 so you can create .yml files for language tests. I still see a bunch of bugs in, for example, Russian, if you feel motivated, appreciate some more tests on top of this, please.
